on:
    push:
      branches:
        - 'main'
      paths:
        - '**/*'
        - '!docs'
    workflow_dispatch: null
  
jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'release'
      
      - name: merge latest main
        run: |
          git fetch
          git checkout origin/main .

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 18.16.1
          cache: 'npm'

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
      # build
      - name: build
        run: |
          make

      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Update docs for
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }} - ${{ github.head_ref }}.${{ github.sha }}" || exit 0
          git push
